### PR TITLE
Second refractor of code

### PR DESCRIPTION
**Pull request by TaylorSmith28**
Changes made in this PR:
- Machine now initializes with status automatically set to "Free" and last_service_date set to none
- Fixed some of the previously commented out pylint errors
- Add the description of the pylint errors underneath the commented out pylint codes
- replaced first_or_401() calls with first() calls using a try implementation, and this allows for more specific error returns than just a 404 error return
- All abort calls have been giving a corresponding error message
- flask migrate has been removed as it was not implemented
- removed unused conditionals, variables, and outdated comments
- The 404 error handler has been implemented in init.py
- Additional comment cleanup, and better naming conventions for some variables

### CODE REVIEW

**Comment by TaylorSmith28** [comment]
I would recommend merging this pull request before working on any code of the project. 

Further refractoring can be done on test_api.py.

**Comment by TaylorSmith28** [comment]
Additional changes:
- Updated the file structure: routes and models are included in an app folder, test_api.py was broken out into a tests folder
- Two additional error handlers have been added to init.py (custom_400_errorhandler, custom_500_errorhandler)
- Updated some tests to assert the abort error messages and not just the status codes

**Comment by TaylorSmith28** [comment]
Additional Changes:
- All the error tests now use one test/<error_code> endpoint
- Added three tests for the /login/callback route
- Modified the send notifications route, now works properly
- Wrote a test for a successful send_email however this is not functional and is a TO-DO
- Wrote a test for the /protected route however this is not functional and is a TO-DO
- 5 new tests for user routes. /user/<user_id> now has full test coverage

**Comment by TaylorSmith28** [comment]
Additional Changes:
- Separated tests into files corresponding to their route
- Fixed some of the if-else statements in the machine/<public_id> route
- Wrote tests for the machine routes, code coverage is now 96%
- Overall code coverage is > 95%
- Revised some of the docstrings for the tests

**Review by haydentinker — APPROVED** [review]
Looks good to me

**Pull request merged**
