### PR TITLE
Updated ENDPOINTS.md to reflect current project

### PR DESCRIPTION
**Pull request by Suocesky**

### CODE REVIEW

**Review by TaylorSmith28 — CHANGES_REQUESTED** [review]
GET /machine will not be implemented. Please delete.

**Comment by Suocesky** [comment]
Deleted GET /machine

**Comment by haydentinker** [comment]
In the Post/Machine endpoint I don't think that we should be using requested_id. It should be public_id instead. In addition to that we have two Get/Machine/Dorm endpoints. I believe that one should be Get/Machine/Dorm/Floor. If you make those changes it should be good to merge. Since @TaylorSmith28 reviewed first, I think he will have to do it again once it is ready.

**Comment by haydentinker** [comment]
Also since we just merged the refactor into main make sure that your branch is up to date before we merge your documentation.

**Review by TaylorSmith28 — APPROVED** [review]
Looks good

**Pull request merged**
